# Generated by Django 3.0.2 on 2020-01-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200107_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='email_verified',
        ),
    ]
