# Generated by Django 3.0.2 on 2020-01-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200107_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'github'), ('kakao', 'kakao')], default='email', max_length=50),
        ),
    ]
